version: "3.3"
services:
  statick:
    image: tdenewiler/statick:latest
    container_name: statick
    environment:
      - STATICK_PROFILE=profile.yaml
    volumes:
      - ${STATICK_PACKAGE}:/tmp/statick_package
      - ${STATICK_CONFIG}:/tmp/statick_config
